//
//  WordModel.swift
//  DailyDiction2
//
//  Created by Philipp Ley on 12.01.24.
//

import Foundation

struct Word {
    var word: String
    var definition: String
}

struct Theme {
    var name: String
    var words: [Word]
}

let wordList: [Word] = themes.flatMap { $0.words }
let themes: [Theme] = [
    Theme(name: "Kunst und Literatur", words: [
        Word(word: "Ästhetik", definition: "Die Lehre von der Wahrnehmung und Beurteilung des Schönen, sowohl in der Kunst als auch in der Natur."),
        Word(word: "Allegorie", definition: "Eine symbolische Darstellung, bei der Personen oder Handlungen Ideen oder abstrakte Konzepte repräsentieren."),
        Word(word: "Barock", definition: "Ein üppiger, detailreicher Kunst- und Architekturstil des 17. und frühen 18. Jahrhunderts."),
        Word(word: "Dadaismus", definition: "Eine künstlerische und literarische Bewegung, die während des Ersten Weltkriegs entstand und traditionelle Kunstformen in Frage stellte."),
        Word(word: "Ekphrasis", definition: "Eine literarische Beschreibung oder Kommentierung eines Kunstwerks."),
        Word(word: "Epos", definition: "Ein langes, erzählendes Gedicht, das große Heldentaten und historische Ereignisse darstellt."),
        Word(word: "Expressionismus", definition: "Eine Kunst- und Literaturbewegung, die versucht, innere Gefühle und Emotionen statt der äußeren Realität darzustellen."),
        Word(word: "Paradoxon", definition: "Eine Aussage, die sich scheinbar selbst widerspricht oder dem gesunden Menschenverstand zuwiderläuft, aber bei näherer Betrachtung eine verborgene Wahrheit enthält."),
        Word(word: "Gothic", definition: "Ein Stil in der Literatur und Kunst, der sich durch düstere, mysteriöse und oft übernatürliche Elemente auszeichnet."),
        Word(word: "Impressionismus", definition: "Eine Kunstbewegung, die darauf abzielt, den Eindruck eines Moments oder einer Szene, oft im Freien, mit Licht und Farbe einzufangen."),
        Word(word: "Analogie", definition: "Ein Vergleich zwischen zwei Dingen, der auf der Annahme beruht, dass, wenn sie in bestimmten Aspekten ähnlich sind, sie auch in anderen ähnlich sein könnten."),
        Word(word: "Katharsis", definition: "Die Reinigung oder Läuterung der Emotionen des Publikums durch die Erfahrungen der Charaktere in einem Drama."),
        Word(word: "Kubismus", definition: "Eine Kunstbewegung des frühen 20. Jahrhunderts, die Objekte in abstrakten Formen und geometrischen Fragmenten darstellt."),
        Word(word: "Lyrik", definition: "Eine Form der Poesie, die persönliche Gefühle und Gedanken ausdrückt, oft in kurzen und musikalischen Versen."),
        Word(word: "Metapher", definition: "Eine bildliche Ausdrucksweise, bei der ein Begriff oder eine Phrase für etwas anderes verwendet wird, um eine Vergleichsbeziehung herzustellen."),
        Word(word: "Minimalismus", definition: "Eine Kunst- und Literaturrichtung, die sich durch Einfachheit und Zurückhaltung in der Form und im Inhalt auszeichnet."),
        Word(word: "Narrativ", definition: "Eine erzählte Geschichte oder eine Darstellung von Ereignissen."),
        Word(word: "Neoklassizismus", definition: "Eine Bewegung, die die Kunst und Kultur der Antike wiederbelebt und sich durch Klarheit, Einfachheit und symmetrische Formen auszeichnet."),
        Word(word: "Onomatopöie", definition: "Die Nachahmung eines Geräusches durch ein Wort, dessen Klang dem Geräusch ähnelt."),
        Word(word: "Pathos", definition: "Eine Qualität in der Kunst oder Literatur, die Mitleid, Traurigkeit oder eine tiefe emotionale Erfahrung hervorruft."),
        Word(word: "Perspektive", definition: "Die Darstellung von dreidimensionalen Objekten auf einer zweidimensionalen Oberfläche, um Tiefe und Position im Raum zu simulieren."),
        Word(word: "Poesie", definition: "Eine literarische Form, die sich durch Rhythmus, Metrik und oft Reim auszeichnet, um ästhetische und emotionale Erfahrungen zu vermitteln."),
        Word(word: "Realismus", definition: "Eine Darstellungsweise in Kunst und Literatur, die versucht, die Wirklichkeit genau und ohne Verzierung wiederzugeben."),
        Word(word: "Renaissance", definition: "Eine kulturelle Bewegung, die das Wiedererwachen der Kunst, Literatur und Wissenschaft in Europa markiert, inspiriert von der klassischen Antike."),
        Word(word: "Rokoko", definition: "Ein dekorativer Kunst- und Architekturstil, der durch Leichtigkeit, Eleganz und verspielte Ornamente gekennzeichnet ist."),
        Word(word: "Romantik", definition: "Eine literarische, künstlerische und philosophische Bewegung, die die Betonung auf Emotion, Individualität und die Wertschätzung der Natur legt."),
        Word(word: "Satire", definition: "Eine literarische Gattung, die menschliche Fehler oder Laster durch Spott, Ironie oder andere humoristische Formen kritisiert."),
        Word(word: "Surrealismus", definition: "Eine künstlerische Bewegung, die versucht, die Welt des Unbewussten, der Träume und der Fantasie darzustellen."),
        Word(word: "Symbolismus", definition: "Die Verwendung von Symbolen, um Ideen und Emotionen auszudrücken, oft in einer Weise, die mehrere Interpretationen zulässt."),
        Word(word: "Tragödie", definition: "Eine dramatische Gattung, die durch ernste Themen und oft durch den Untergang oder Tod der Hauptfigur gekennzeichnet ist.")
    ]),
    Theme(name: "Natur und Umwelt", words: [
        Word(word: "Biodiversität", definition: "Die Vielfalt des Lebens in allen Formen, Ebenen und Kombinationen, einschließlich der Ökosystem-Vielfalt, Artenvielfalt und genetischen Vielfalt."),
        Word(word: "Biome", definition: "Große Gemeinschaften von Pflanzen und Tieren, die sich durch die klimatischen und geografischen Bedingungen eines großen Gebietes entwickeln."),
        Word(word: "Chlorophyll", definition: "Ein grüner Farbstoff in Pflanzen, Algen und einigen Bakterien, der für die Photosynthese unerlässlich ist."),
        Word(word: "Detritus", definition: "Organisches Material, das von abgestorbenen Organismen stammt und durch Zersetzung im Ökosystem recycelt wird."),
        Word(word: "Erosion", definition: "Der Prozess, durch den Boden und Gestein von der Erdoberfläche durch natürliche Kräfte wie Wasser, Wind oder Eis entfernt werden."),
        Word(word: "Fauna", definition: "Die Gesamtheit der Tierarten, die in einem bestimmten Gebiet oder zu einer bestimmten Zeit auf der Erde leben."),
        Word(word: "Flora", definition: "Die Gesamtheit der Pflanzenarten, die in einem bestimmten Gebiet oder zu einer bestimmten Zeit auf der Erde leben."),
        Word(word: "Geothermie", definition: "Die Wissenschaft und Technologie, die sich mit der Nutzung der in der Erde gespeicherten Wärmeenergie befasst."),
        Word(word: "Habitat", definition: "Der natürliche Lebensraum oder die Umgebung, in der eine Pflanze, ein Tier oder eine andere Organismenart lebt und gedeiht."),
        Word(word: "Herbivore", definition: "Ein Tier, das sich hauptsächlich von Pflanzen ernährt."),
        Word(word: "Hydrosphäre", definition: "Die Gesamtheit allen Wassers auf, über und unter der Oberfläche der Erde."),
        Word(word: "Karbonisierung", definition: "Der Prozess der Umwandlung von organischem Material in Kohle durch den Einfluss von Hitze und Druck über geologische Zeiträume."),
        Word(word: "Klimaxgemeinschaft", definition: "Eine stabile Gemeinschaft, die das Endstadium der ökologischen Sukzession in einem bestimmten Gebiet darstellt."),
        Word(word: "Konservierung", definition: "Der Schutz und die Erhaltung natürlicher Ressourcen und Ökosysteme durch gezielte Maßnahmen und Strategien."),
        Word(word: "Lithosphäre", definition: "Die äußerste feste Schicht der Erde, die aus der Erdkruste und dem obersten Teil des Erdmantels besteht."),
        Word(word: "Mangroven", definition: "Tropische Pflanzen, die in salzigen oder brackigen Gewässern in Küstennähe wachsen und wichtige Ökosysteme bilden."),
        Word(word: "Nekton", definition: "Die Gesamtheit aller schwimmfähigen Organismen im Wasser, die gegen Strömungen anschwimmen können, im Gegensatz zu Plankton."),
        Word(word: "Omnivore", definition: "Ein Tier, das sich sowohl von Pflanzen als auch von Fleisch ernährt."),
        Word(word: "Photosynthese", definition: "Der Prozess, durch den grüne Pflanzen und einige andere Organismen Sonnenlicht nutzen, um aus Kohlendioxid und Wasser Nahrung in Form von Glukose zu produzieren und dabei Sauerstoff freisetzen."),
        Word(word: "Pollination", definition: "Der Vorgang der Übertragung von Pollen von den männlichen Teilen einer Blüte zu den weiblichen Teilen, was zur Bestäubung und anschließenden Samenbildung führt."),
        Word(word: "Savanne", definition: "Ein Grasland-Ökosystem, charakterisiert durch das Vorhandensein vereinzelter Bäume und eine saisonale Regen- und Trockenzeit."),
        Word(word: "Symbiose", definition: "Eine enge und oft langfristige Interaktion zwischen zwei verschiedenen biologischen Arten, die für mindestens eine der Arten vorteilhaft ist."),
        Word(word: "Taiga", definition: "Ein Waldökosystem, das in den nördlichen Regionen der Erde vorherrscht, gekennzeichnet durch Nadelbäume und ein kühles Klima."),
        Word(word: "Tundra", definition: "Ein Ökosystem, das durch extrem kalte Temperaturen und kurze Wachstumsperioden gekennzeichnet ist, mit einer Vegetation, die hauptsächlich aus Moosen, Flechten und Gräsern besteht."),
        Word(word: "Umweltverschmutzung", definition: "Die Einführung von Schadstoffen in die natürliche Umwelt, die negative Auswirkungen auf die Umwelt und die Lebewesen haben kann."),
        Word(word: "Vulkanismus", definition: "Die geologische Aktivität, die mit dem Aufstieg von Magma, Asche und Gasen an die Erdoberfläche verbunden ist, was zur Bildung von Vulkanen führt."),
        Word(word: "Wetland", definition: "Ein Gebiet, das regelmäßig überschwemmt wird oder dessen Boden permanent mit Wasser gesättigt ist, was eine einzigartige Flora und Fauna unterstützt."),
        Word(word: "Xerophyt", definition: "Eine Pflanze, die an trockene, wasserarme Bedingungen angepasst ist."),
        Word(word: "Zonation", definition: "Die räumliche oder vertikale Anordnung von Pflanzen- oder Tiergemeinschaften in einem bestimmten Gebiet aufgrund von Umweltgradienten wie Tiefe, Höhe oder Salzgehalt."),
        Word(word: "Ökotone", definition: "Ein Übergangsbereich zwischen zwei unterschiedlichen Ökosystemen oder Biomen, in dem sich Elemente beider angrenzender Systeme vermischen und eine hohe Artenvielfalt und ökologische Vielfalt aufweisen können.")
    ]),

    Theme(name: "Technologie und Innovation", words: [
        Word(word: "Algorithmus", definition: "Eine definierte Folge von Anweisungen für die Ausführung einer Aufgabe oder Lösung eines Problems."),
        Word(word: "Blockchain", definition: "Eine Technologie für eine dezentrale Datenhaltung, die Transaktionen sicher und nachvollziehbar speichert."),
        Word(word: "Kryptografie", definition: "Die Wissenschaft der Verschlüsselung von Informationen zum Schutz vor unbefugtem Zugriff."),
        Word(word: "Datenmigration", definition: "Der Prozess des Übertragens von Daten zwischen verschiedenen Speicherorten, Formaten oder Systemen."),
        Word(word: "E-Commerce", definition: "Der elektronische Handel über das Internet, der den Kauf und Verkauf von Waren und Dienstleistungen umfasst."),
        Word(word: "Fintech", definition: "Kurz für Finanztechnologie; bezieht sich auf den Einsatz von Technologien in Finanzdienstleistungen."),
        Word(word: "Gigabit", definition: "Ein Maß für digitale Datenübertragungskapazität oder Speichergröße, gleich 1 Milliarde Bits."),
        Word(word: "Holographie", definition: "Eine Technik zur Erzeugung von dreidimensionalen Bildern mithilfe von Laserlicht."),
        Word(word: "Internet der Dinge", definition: "Die Vernetzung von physischen Geräten mit dem Internet, um Daten auszutauschen und Funktionen zu automatisieren."),
        Word(word: "Autonome Systeme", definition: "Systeme, die ohne menschliche Intervention Aufgaben ausführen, oft basierend auf Künstlicher Intelligenz."),
        Word(word: "Machine Learning", definition: "Ein Teilgebiet der KI, das Maschinen das Lernen aus Daten ermöglicht, ohne explizit programmiert zu sein."),
        Word(word: "Nanotechnologie", definition: "Die Manipulation von Materie auf atomarer und molekularer Ebene, um neuartige Materialien und Geräte zu schaffen."),
        Word(word: "Quantencomputing", definition: "Eine Form der Datenverarbeitung, die die Prinzipien der Quantenmechanik nutzt, um komplexe Probleme effizient zu lösen."),
        Word(word: "Mensch-Maschine-Interaktion", definition: "Das Studium der Interaktionen zwischen Menschen und Computern oder anderen Maschinen."),
        Word(word: "Agile Entwicklung", definition: "Eine flexible und iterative Methode der Softwareentwicklung, die sich auf die Anpassungsfähigkeit an Veränderungen konzentriert."),
        Word(word: "Telematik", definition: "Die Integration von Telekommunikations- und Informationstechnologien, insbesondere im Fahrzeugkontext."),
        Word(word: "Digitale Ethik", definition: "Die Untersuchung ethischer Fragen, die mit der Nutzung digitaler Technologien und Daten verbunden sind."),
        Word(word: "Mixed Reality", definition: "Eine Technologie, die reale und virtuelle Welten vermischt, um neue Umgebungen zu schaffen, in denen physische und digitale Objekte interagieren können."),
        Word(word: "Bioinformatik", definition: "Die Anwendung von Informatikmethoden auf biologische Daten, insbesondere in der Genomik und Molekularbiologie."),
        Word(word: "3D-Druck", definition: "Ein Fertigungsverfahren, bei dem Material schichtweise aufgetragen wird, um dreidimensionale Objekte aus digitalen Modellen zu erstellen."),
        Word(word: "Augmented Reality", definition: "Eine Technologie, die computergenerierte Informationen über die reale Welt legt, um diese zu erweitern oder zu ergänzen."),
        Word(word: "Data Mining", definition: "Der Prozess des Extrahierens nützlicher Informationen aus großen Datenmengen durch Identifizierung von Mustern und Trends."),
        Word(word: "Cloud-Computing", definition: "Die Bereitstellung von Rechenressourcen (wie Servern, Speicher, Datenbanken) über das Internet auf Abrufbasis."),
        Word(word: "E-Government", definition: "Die Nutzung elektronischer Kommunikationsmittel und Informationstechnologien durch Regierungsorganisationen zur Verbesserung der Dienstleistungen und Interaktionen mit Bürgern."),
        Word(word: "Ethernet", definition: "Eine weit verbreitete Technologie für lokale Computernetzwerke (LANs), die Geräte innerhalb eines Gebäudes oder Campus verbindet."),
        Word(word: "RFID", definition: "Eine Technologie, die die drahtlose Nutzung elektromagnetischer Felder zur Identifizierung und Nachverfolgung von Tags an Objekten ermöglicht."),
        Word(word: "Hyperlink", definition: "Ein Element in einem elektronischen Dokument, das beim Anklicken den Benutzer zu einem anderen Dokument oder einer anderen Ressource führt."),
        Word(word: "Informationsarchitektur", definition: "Die Kunst und Wissenschaft der Strukturierung und Organisation von Informationen, um ihre Auffindbarkeit und Benutzbarkeit zu verbessern."),
        Word(word: "Neuronale Netze", definition: "Computernetzwerke, die nach dem Vorbild der neuronalen Netzwerke des menschlichen Gehirns gestaltet sind, um Lernaufgaben durchzuführen."),
        Word(word: "Internet of Everything", definition: "Ein erweitertes Konzept, das nicht nur Geräte (IoT), sondern auch Menschen, Daten und Prozesse miteinander vernetzt, um umfassendere Lösungen und Erfahrungen zu ermöglichen.")
    ]),

    Theme(name: "Gesellschaft und Politik", words: [
        Word(word: "Demokratie", definition: "Ein politisches System, in dem die Macht durch gewählte Vertreter des Volkes oder direkt durch das Volk selbst ausgeübt wird."),
        Word(word: "Autokratie", definition: "Eine Regierungsform, in der eine einzelne Person (Autokrat) uneingeschränkte Macht besitzt."),
        Word(word: "Föderalismus", definition: "Ein politisches Konzept, bei dem die Macht zwischen einer zentralen (nationalen) Regierung und mehreren regionalen Regierungen aufgeteilt ist."),
        Word(word: "Globalisierung", definition: "Der Prozess der zunehmenden internationalen Vernetzung in den Bereichen Wirtschaft, Politik, Kultur und Umwelt."),
        Word(word: "Ideologie", definition: "Ein System von Ideen und Idealen, insbesondere eines, das die Basis für wirtschaftliche oder politische Theorien und Politiken bildet."),
        Word(word: "Kapitalismus", definition: "Ein Wirtschaftssystem, in dem Handel, Industrie und die Produktionsmittel im Besitz privater Unternehmen sind, die nach Gewinn streben."),
        Word(word: "Kommunismus", definition: "Eine politische und wirtschaftliche Ideologie, die eine klassenlose Gesellschaft anstrebt, in der alle Produktionsmittel gemeinschaftlich besessen sind."),
        Word(word: "Legitimität", definition: "Die allgemeine Anerkennung und Akzeptanz der Autorität einer Regierung oder eines Regimes."),
        Word(word: "Neoliberalismus", definition: "Eine politische Richtung, die freie Märkte, Privatisierung, geringere staatliche Intervention in die Wirtschaft und Reduzierung der Ausgaben für soziale Dienste betont."),
        Word(word: "Oligarchie", definition: "Eine Regierungsform, in der die Macht in den Händen einer kleinen Gruppe von Menschen konzentriert ist."),
        Word(word: "Parlamentarismus", definition: "Ein Regierungssystem, in dem die Exekutivgewalt von einer Legislative (Parlament) abhängig ist und ihr gegenüber verantwortlich ist."),
        Word(word: "Pluralismus", definition: "Eine politische Theorie oder ein System, das die Existenz und die friedliche Koexistenz verschiedener Interessen, Überzeugungen und Lebensstile unterstützt."),
        Word(word: "Populismus", definition: "Ein politischer Ansatz, der versucht, die Interessen und Ansichten der 'gewöhnlichen Menschen' anzusprechen, oft durch die Gegenüberstellung gegen eine 'Elite'."),
        Word(word: "Säkularismus", definition: "Das Prinzip der Trennung von Staat und religiösen Institutionen."),
        Word(word: "Sozialismus", definition: "Eine politische und wirtschaftliche Theorie der sozialen Organisation, die darauf abzielt, Produktion, Verteilung und Austausch zu regulieren und Gemeineigentum oder staatliche Kontrolle der Produktionsmittel zu fördern."),
        Word(word: "Souveränität", definition: "Die oberste Macht oder Autorität eines Staates, sich selbst zu regieren und seine eigenen Gesetze zu bestimmen."),
        Word(word: "Subsidiarität", definition: "Ein Organisationsprinzip, das besagt, dass Entscheidungen so nah wie möglich am Bürger getroffen werden sollten."),
        Word(word: "Totalitarismus", definition: "Ein politisches System, in dem der Staat nahezu vollständige Kontrolle über das öffentliche und private Leben hat."),
        Word(word: "Utopie", definition: "Eine imaginäre Gemeinschaft oder Gesellschaft mit höchst wünschenswerten oder nahezu perfekten Eigenschaften."),
        Word(word: "Wohlfahrtsstaat", definition: "Ein Regierungssystem, das versucht, das Wohlergehen seiner Bürger durch Programme wie Gesundheitsfürsorge, Bildung und Sozialhilfe zu schützen und zu fördern."),
        Word(word: "Xenophobie", definition: "Die Angst oder Abneigung gegenüber Menschen aus anderen Ländern oder Kulturen."),
        Word(word: "Zivilgesellschaft", definition: "Der Bereich des gesellschaftlichen Lebens, der unabhängig von der Regierung und dem Markt organisiert ist und in dem sich Menschen freiwillig für gemeinsame Zwecke zusammenschließen."),
        Word(word: "Nachhaltigkeit", definition: "Die Praxis der Erhaltung von Ressourcen, um ökologische, soziale und wirtschaftliche Anforderungen für zukünftige Generationen zu erfüllen."),
        Word(word: "Multilateralismus", definition: "Die Zusammenarbeit von mehreren Ländern in Bezug auf eine Angelegenheit von gemeinsamem Interesse."),
        Word(word: "NGO", definition: "Eine gemeinnützige Organisation, die unabhängig von staatlicher Kontrolle operiert und sich oft für soziale oder politische Ziele einsetzt."),
        Word(word: "Gentrifizierung", definition: "Der Prozess der Erneuerung und Verbesserung eines Viertels, so dass es den Mittel- und Oberschichten entspricht, was oft zur Verdrängung der ursprünglichen, ärmeren Bewohner führt."),
        Word(word: "Diaspora", definition: "Die Verbreitung von Menschen aus einer nationalen oder ethnischen Gruppe über verschiedene Länder."),
        Word(word: "E-Governance", definition: "Die Anwendung von Informations- und Kommunikationstechnologien zur Verbesserung der Dienstleistungen und der Interaktion zwischen Regierung und Bürgern, Unternehmen und anderen Regierungseinheiten."),
        Word(word: "Hegemonie", definition: "Die Vorherrschaft oder Überlegenheit eines Staates oder einer sozialen Gruppe über andere.")
    ]),

    Theme(name: "Wirtschaft und Finanzen", words: [
        Word(word: "Makroökonomie", definition: "Der Teil der Wirtschaftswissenschaft, der sich mit den Leistungen, Strukturen und dem Verhalten der Wirtschaft als Ganzes befasst."),
        Word(word: "Mikroökonomie", definition: "Studiert individuelle Marktteilnehmer, Haushalte und Unternehmen sowie deren Interaktionen."),
        Word(word: "Inflation", definition: "Der Anstieg des allgemeinen Preisniveaus von Waren und Dienstleistungen in einer Wirtschaft über einen Zeitraum hinweg."),
        Word(word: "Deflation", definition: "Ein Rückgang des allgemeinen Preisniveaus von Waren und Dienstleistungen, oft verbunden mit einer Reduzierung der Geldmenge und des Kreditvolumens."),
        Word(word: "Bruttoinlandsprodukt", definition: "Der Gesamtwert aller in einem Land innerhalb eines bestimmten Zeitraums produzierten Waren und Dienstleistungen."),
        Word(word: "Fiskalpolitik", definition: "Die Nutzung der Staatsausgaben und Besteuerung zur Beeinflussung der Wirtschaft."),
        Word(word: "Geldpolitik", definition: "Die Steuerung der Geldmenge und des Zinssatzes durch eine Zentralbank zur Steuerung von Inflation und Wirtschaftswachstum."),
        Word(word: "Arbeitslosenquote", definition: "Der Prozentsatz der Arbeitskräfte, die arbeitslos und aktiv auf der Suche nach Arbeit sind."),
        Word(word: "Stagflation", definition: "Eine Situation, in der die Inflationsrate hoch ist, das Wirtschaftswachstum langsam und die Arbeitslosigkeit beständig hoch bleibt."),
        Word(word: "Rezession", definition: "Eine signifikante, allgemeine und anhaltende Abschwächung der Wirtschaftstätigkeit."),
        Word(word: "Kapitalmarkt", definition: "Ein Markt, auf dem langfristige Finanzinstrumente wie Aktien und Anleihen gehandelt werden."),
        Word(word: "Liquidität", definition: "Die Fähigkeit, Vermögenswerte schnell in Bargeld umzuwandeln, ohne dabei signifikant an Wert zu verlieren."),
        Word(word: "Portfolio", definition: "Die Gesamtheit der Investitionen, die eine Person oder Institution hält."),
        Word(word: "Rendite", definition: "Die Einnahmen aus einer Investition, oft ausgedrückt als Prozentsatz des investierten Kapitals."),
        Word(word: "Volatilität", definition: "Das Ausmaß der Schwankung der Handelspreise innerhalb eines bestimmten Zeitraums."),
        Word(word: "Hedgefonds", definition: "Ein Investmentfonds, der mit fortgeschrittenen Strategien arbeitet, um positive Renditen unabhängig von der Marktrichtung zu erzielen."),
        Word(word: "Leverage-Effekt", definition: "Die Nutzung von Fremdkapital, um das Potenzial für Rendite einer Investition zu erhöhen."),
        Word(word: "Diversifikation", definition: "Eine Risikomanagementstrategie, die verschiedene Investitionen innerhalb eines Portfolios mischt, um das Risiko zu verringern."),
        Word(word: "Derivat", definition: "Ein Finanzinstrument, dessen Wert von der Wertentwicklung eines anderen Vermögenswerts abhängt."),
        Word(word: "Kreditwürdigkeit", definition: "Die Einschätzung der Fähigkeit eines Kreditnehmers, seine Schulden zurückzuzahlen."),
        Word(word: "Insolvenz", definition: "Der Zustand, in dem ein Unternehmen oder eine Person unfähig ist, seine Schulden zu begleichen."),
        Word(word: "Subvention", definition: "Eine finanzielle Unterstützung, die von der Regierung an Unternehmen, Organisationen oder Einzelpersonen gewährt wird, um eine wirtschaftliche Aktivität zu fördern."),
        Word(word: "Handelsbilanz", definition: "Die Differenz zwischen dem Wert der Exporte und Importe eines Landes über einen bestimmten Zeitraum."),
        Word(word: "Devisenmarkt", definition: "Der Markt, auf dem Währungen gekauft und verkauft werden, und der die Wechselkurse zwischen den Währungen bestimmt."),
        Word(word: "Bruttosozialprodukt", definition: "Eine Maßzahl für die wirtschaftliche Leistung eines Landes, die den Gesamtwert aller Waren und Dienstleistungen berücksichtigt, die von den Bürgern eines Landes in einem bestimmten Zeitraum produziert wurden."),
        Word(word: "Kapitalertragssteuer", definition: "Eine Steuer auf den Gewinn, der aus dem Verkauf von Vermögenswerten oder Investitionen erzielt wird."),
        Word(word: "Monopol", definition: "Die exklusive Kontrolle oder das Besitzverhältnis eines Sektors oder einer Branche durch ein einzelnes Unternehmen, das den Markt beherrscht."),
        Word(word: "Oligopol", definition: "Ein Markt, der von einer kleinen Anzahl von Unternehmen beherrscht wird, die zusammen erheblichen Einfluss ausüben können."),
        Word(word: "Preisfixierung", definition: "Ein illegales Abkommen zwischen Konkurrenten, Preise auf einem bestimmten Niveau festzulegen oder zu halten."),
        Word(word: "Indexfonds", definition: "Ein Investmentfonds oder börsengehandelter Fonds (ETF), der darauf abzielt, die Rendite eines spezifischen Marktindex zu replizieren.")
    ]),

    Theme(name: "Gesundheit und Medizin", words: [
        Word(word: "Anatomie", definition: "Die Wissenschaft von der Struktur des Körpers von Lebewesen."),
        Word(word: "Physiologie", definition: "Die Wissenschaft von den normalen Funktionen lebender Organismen und ihrer Teile."),
        Word(word: "Epidemiologie", definition: "Das Studium der Verteilung und Determinanten von Gesundheitszuständen oder Ereignissen in spezifischen Populationen."),
        Word(word: "Pathologie", definition: "Die Wissenschaft von den Ursachen und Wirkungen von Krankheiten, insbesondere die Untersuchung von Gewebeproben und Körperflüssigkeiten."),
        Word(word: "Diagnose", definition: "Die Identifizierung einer Krankheit oder eines Zustandes durch systematische Untersuchung der Symptome."),
        Word(word: "Therapie", definition: "Die Behandlung eines Krankheitszustandes, insbesondere durch Heilung, Linderung oder Vorbeugung."),
        Word(word: "Prognose", definition: "Eine Vorhersage des wahrscheinlichen Verlaufs und Ausgangs einer Krankheit."),
        Word(word: "Prävention", definition: "Maßnahmen zur Vermeidung des Auftretens von Krankheiten oder anderen gesundheitlichen Problemen."),
        Word(word: "Vakzination", definition: "Die Verabreichung eines Impfstoffs, um Immunität gegen eine bestimmte Krankheit zu erzeugen."),
        Word(word: "Pharmakologie", definition: "Die Wissenschaft von der Wirkung von Medikamenten und deren Anwendung bei der Behandlung von Krankheiten."),
        Word(word: "Radiologie", definition: "Das medizinische Fachgebiet, das sich mit der Verwendung bildgebender Verfahren zur Diagnose und Behandlung von Krankheiten befasst."),
        Word(word: "Chirurgie", definition: "Der Bereich der Medizin, der sich mit der Behandlung von Krankheiten, Verletzungen und Deformitäten durch manuelle und instrumentelle Techniken befasst."),
        Word(word: "Onkologie", definition: "Das Studium und die Behandlung von Tumoren und Krebs."),
        Word(word: "Kardiologie", definition: "Das medizinische Fachgebiet, das sich mit Erkrankungen des Herzens und des Kreislaufsystems befasst."),
        Word(word: "Dermatologie", definition: "Das medizinische Fachgebiet, das sich mit der Haut und ihren Erkrankungen befasst."),
        Word(word: "Endokrinologie", definition: "Die Wissenschaft von den Hormonen und den Drüsen, die sie ausschütten."),
        Word(word: "Gastroenterologie", definition: "Das medizinische Fachgebiet, das sich mit dem Verdauungssystem und seinen Störungen befasst."),
        Word(word: "Neurologie", definition: "Das medizinische Fachgebiet, das sich mit Erkrankungen des Nervensystems befasst."),
        Word(word: "Pädiatrie", definition: "Das medizinische Fachgebiet, das sich mit der medizinischen Versorgung von Neugeborenen, Kindern und Jugendlichen befasst."),
        Word(word: "Psychiatrie", definition: "Das medizinische Fachgebiet, das sich mit der Diagnose, Behandlung und Prävention psychischer Störungen befasst."),
        Word(word: "Rheumatologie", definition: "Das medizinische Fachgebiet, das sich mit rheumatischen Erkrankungen, d.h. mit entzündlichen und degenerativen Erkrankungen des Bewegungsapparates befasst."),
        Word(word: "Toxikologie", definition: "Die Wissenschaft von den Giften, ihren Wirkungen und der Behandlung von Vergiftungen."),
        Word(word: "Urologie", definition: "Das medizinische Fachgebiet, das sich mit den Harnorganen bei beiden Geschlechtern und den Geschlechtsorganen beim männlichen Geschlecht befasst."),
        Word(word: "Virologie", definition: "Die Wissenschaft, die sich mit Viren und Viruskrankheiten befasst."),
        Word(word: "Gerontologie", definition: "Das Studium des Alterns und der Probleme älterer Menschen."),
        Word(word: "Immunologie", definition: "Das Studium des Immunsystems und seiner Reaktionen auf Bedrohungen für die Gesundheit."),
        Word(word: "Ophthalmologie", definition: "Das medizinische Fachgebiet, das sich mit den Augen und ihren Krankheiten befasst."),
        Word(word: "Orthopädie", definition: "Das medizinische Fachgebiet, das sich mit der Vorbeugung und Korrektur von Deformitäten oder Funktionsstörungen des Bewegungsapparates befasst."),
        Word(word: "Palliativmedizin", definition: "Die medizinische Versorgung und Behandlung von Patienten mit schweren, oft fortschreitenden Krankheiten, mit dem Ziel, die Lebensqualität zu verbessern."),
        Word(word: "Ergotherapie", definition: "Eine Form der Therapie, die Menschen dabei hilft, durch spezifische Aktivitäten oder Anpassungen an ihre Umgebung wieder in den Alltag zurückzukehren oder ihre Fähigkeiten zu verbessern.")
    ]),

    Theme(name: "Sprache und Linguistik", words: [
        Word(word: "Phonetik", definition: "Die Wissenschaft von den Lauten menschlicher Sprache."),
        Word(word: "Phonologie", definition: "Das Studium der systematischen Organisation von Lauten in Sprachen."),
        Word(word: "Morphologie", definition: "Die Untersuchung der Struktur und Bildung von Wörtern."),
        Word(word: "Syntax", definition: "Das Studium der Regeln und Prinzipien, die den Satzbau in Sprachen bestimmen."),
        Word(word: "Semantik", definition: "Das Gebiet, das sich mit der Bedeutung von Wörtern, Phrasen und Sätzen befasst."),
        Word(word: "Pragmatik", definition: "Die Untersuchung, wie der Kontext die Bedeutung beeinflusst."),
        Word(word: "Soziolinguistik", definition: "Das Studium der Beziehungen zwischen Sprache und Gesellschaft und der Art und Weise, wie Sprache in sozialen Kontexten verwendet wird."),
        Word(word: "Dialektologie", definition: "Das Studium der geografischen Verteilung von Sprachvariationen und Dialekten."),
        Word(word: "Psycholinguistik", definition: "Die Untersuchung psychologischer und neurobiologischer Faktoren, die das Erlernen und Verwenden von Sprache ermöglichen."),
        Word(word: "Linguistische Anthropologie", definition: "Die Untersuchung der Wechselbeziehungen zwischen Sprache und Kultur."),
        Word(word: "Korpuslinguistik", definition: "Die Analyse und das Studium der Sprache durch große Sammlungen von 'echten' Texten, bekannt als Korpora."),
        Word(word: "Etymologie", definition: "Das Studium der Herkunft von Wörtern und der Art und Weise, wie sich ihre Bedeutungen und Formen im Laufe der Zeit verändert haben."),
        Word(word: "Orthographie", definition: "Das Studium der Rechtschreibung und Schreibsysteme."),
        Word(word: "Semiotik", definition: "Die Untersuchung von Zeichen und Symbolen und ihrer Verwendung oder Interpretation."),
        Word(word: "Diskursanalyse", definition: "Die Untersuchung sprachlicher Einheiten, die größer als ein Satz sind, insbesondere der Strukturen und Funktionen von Gesprächen oder Texten."),
        Word(word: "Transkription", definition: "Die systematische Darstellung von Sprachlauten mit schriftlichen Symbolen."),
        Word(word: "Bilingualismus", definition: "Die Fähigkeit, zwei Sprachen fließend zu sprechen."),
        Word(word: "Multilingualismus", definition: "Die Fähigkeit, mehrere Sprachen fließend zu sprechen."),
        Word(word: "Pidgin", definition: "Eine vereinfachte Sprache, die sich aus dem Kontakt zwischen Sprechern unterschiedlicher Muttersprachen entwickelt."),
        Word(word: "Kreolsprache", definition: "Eine stabilisierte natürliche Sprache, die sich aus dem Mischen mehrerer Sprachen entwickelt hat."),
        Word(word: "Paläolinguistik", definition: "Das Studium alter und ausgestorbener Sprachen."),
        Word(word: "Neologismus", definition: "Ein neu geprägtes Wort, Ausdruck oder eine neue Bedeutung."),
        Word(word: "Lexikologie", definition: "Das Studium des Wortschatzes und der Wortbildung."),
        Word(word: "Grammatikalisierung", definition: "Der Prozess, durch den Wörter oder Phrasen von lexikalischen zu grammatischen Elementen werden."),
        Word(word: "Interlinguistik", definition: "Das Studium der Schaffung und des Gebrauchs von Plansprachen zu verschiedenen Zwecken."),
        Word(word: "Forensische Linguistik", definition: "Die Anwendung linguistischer Kenntnisse, Methoden und Erkenntnisse auf das Rechtssystem, insbesondere zur Klärung der Autor- oder Sprecheridentifikation."),
        Word(word: "Spracherwerb", definition: "Der Prozess, durch den Menschen Sprache(n) lernen und beherrschen."),
        Word(word: "Sprachpathologie", definition: "Das Studium von Sprachstörungen und deren Diagnose und Behandlung."),
        Word(word: "Sprachplanung", definition: "Der bewusste Versuch, die Funktionen, Strukturen oder den Gebrauch einer Sprache innerhalb einer Gemeinschaft, oft für soziale oder politische Zwecke, zu beeinflussen."),
        Word(word: "Sprachkontakt", definition: "Die Interaktion zwischen Sprechern verschiedener Sprachen, die zur Übernahme von Merkmalen zwischen diesen Sprachen führt.")
    ]),
    Theme(name: "Philosophie und Psychologie", words: [
        Word(word: "Epistemologie", definition: "Die Theorie des Wissens, die sich mit den Ursprüngen, der Struktur, den Methoden und der Gültigkeit von Erkenntnis beschäftigt."),
        Word(word: "Ontologie", definition: "Der Zweig der Metaphysik, der sich mit der Natur des Seins, der Existenz und der Realität befasst."),
        Word(word: "Dialektik", definition: "Eine Methode des Dialogs oder der Argumentation, bei der Gegensätze diskutiert und Lösungen oder Synthesen gefunden werden."),
        Word(word: "Ethik", definition: "Die philosophische Untersuchung von Moral, Tugend und guten Handlungsweisen."),
        Word(word: "Phänomenologie", definition: "Die philosophische Untersuchung von Strukturen des Bewusstseins und Phänomenen, wie sie aus der Ersten-Person-Perspektive erlebt werden."),
        Word(word: "Existentialismus", definition: "Eine philosophische Theorie, die die freie Wahl, den freien Willen und die individuelle Bedeutung in den Mittelpunkt stellt."),
        Word(word: "Utilitarismus", definition: "Eine ethische Theorie, die das größte Glück der größten Zahl als das größte Gut betrachtet."),
        Word(word: "Deontologie", definition: "Eine ethische Theorie, die die Wichtigkeit von Pflichten und Regeln betont, unabhängig von den Konsequenzen."),
        Word(word: "Hedonismus", definition: "Die Überzeugung, dass das Streben nach Vergnügen und die Vermeidung von Schmerz die Hauptziele im Leben sind."),
        Word(word: "Kognition", definition: "Die mentalen Aktions- oder Prozessaspekte des Erkennens, einschließlich Aufmerksamkeit, Gedächtnis, Urteilsvermögen und Problemlösung."),
        Word(word: "Neuroplastizität", definition: "Die Fähigkeit des Gehirns, sich als Reaktion auf Lernen, Erfahrung oder Verletzung zu verändern und neu zu organisieren."),
        Word(word: "Psychoanalyse", definition: "Eine Methode zur Untersuchung des Geistes und zur Behandlung psychischer Störungen, die auf den Theorien von Sigmund Freud basiert."),
        Word(word: "Behaviorismus", definition: "Ein Ansatz in der Psychologie, der sich auf beobachtbares Verhalten und dessen Erklärung durch Lernprinzipien konzentriert."),
        Word(word: "Kognitive Dissonanz", definition: "Ein Zustand psychologischen Konflikts, der aus inkonsistenten Überzeugungen und Einstellungen resultiert."),
        Word(word: "Gestalttherapie", definition: "Ein psychotherapeutischer Ansatz, der die ganzheitliche Erfahrung und das gegenwärtige Moment betont."),
        Word(word: "Humanismus", definition: "Eine philosophische und ethische Haltung, die den Wert und die Handlungsfähigkeit des Menschen betont."),
        Word(word: "Determinismus", definition: "Die Theorie, dass alle Ereignisse, einschließlich moralischer Entscheidungen, durch vorhergehende Ursachen bestimmt sind."),
        Word(word: "Empirismus", definition: "Die Theorie, dass alle Wissensansprüche aus der Erfahrung abgeleitet und durch die Sinne verifiziert werden müssen."),
        Word(word: "Rationalismus", definition: "Die Überzeugung, dass Vernunft die Hauptquelle des Wissens ist."),
        Word(word: "Dualismus", definition: "Die Ansicht, dass die geistige und die physische (oder materielle) Welt unterschiedlich und getrennt sind."),
        Word(word: "Monismus", definition: "Die philosophische Position, dass alles auf eine einzige Substanz oder Realität zurückgeführt werden kann."),
        Word(word: "Relativismus", definition: "Die Idee, dass Wahrheit, Moral und Werte nicht absolut sind, sondern nur in Bezug auf Kultur, Gesellschaft oder historischen Kontext verstanden werden können."),
        Word(word: "Nihilismus", definition: "Die Überzeugung, dass alle Werte grundlos sind und dass das Leben keinen Sinn hat."),
        Word(word: "Phänomenalismus", definition: "Die Auffassung, dass physische Objekte und Ereignisse als Phänomenbündel oder -konstellationen verstanden werden sollten."),
        Word(word: "Positivismus", definition: "Eine philosophische Richtung, die besagt, dass das einzige authentische Wissen das ist, das auf Sinneserfahrung und positiver Verifizierung basiert."),
        Word(word: "Pragmatismus", definition: "Eine philosophische Tradition, die die praktischen Aspekte von Ideen und Konzepten betont."),
        Word(word: "Reduktionismus", definition: "Der Ansatz, komplexe Phänomene auf ihre einfachsten Bestandteile oder deren Interaktionen zu reduzieren."),
        Word(word: "Solipsismus", definition: "Die philosophische Idee, dass nur das eigene Ich und seine Erfahrungen sicher bekannt sind.")
    ]),
    
    Theme(name: "Gastronomie und Kulinarisches", words: [
        Word(word: "Sous-vide", definition: "Eine Methode des Kochens, bei der Lebensmittel in einem luftdichten Beutel im Wasserbad bei sehr präzisen, niedrigen Temperaturen gegart werden."),
        Word(word: "Umami", definition: "Bezeichnet als fünfter Grundgeschmack neben süß, sauer, bitter und salzig, der oft als herzhaft oder fleischig beschrieben wird."),
        Word(word: "Fermentation", definition: "Der chemische Abbau von Substanzen durch Bakterien, Hefen oder andere Mikroorganismen, oft verwendet in der Lebensmittelherstellung."),
        Word(word: "Molekularküche", definition: "Ein moderner Kochstil, der wissenschaftliche Methoden und Prinzipien nutzt, um neue Texturen und Geschmackserlebnisse zu schaffen."),
        Word(word: "Confit", definition: "Eine traditionelle französische Methode, Lebensmittel langsam in Fett zu garen, um sie zu konservieren."),
        Word(word: "Degustation", definition: "Eine sorgfältige, schätzenswerte Verkostung von verschiedenen Speisen, oft mit dem Ziel, die sensorischen Eigenschaften zu bewerten."),
        Word(word: "Marinieren", definition: "Das Einlegen von Lebensmitteln in eine Mischung aus Säuren, Ölen und Gewürzen, um Geschmack zu verleihen und oft das Fleisch zarter zu machen."),
        Word(word: "Coulis", definition: "Ein glattes Püree aus Gemüse oder Früchten, das oft als Sauce verwendet wird."),
        Word(word: "Duxelles", definition: "Eine fein gehackte Mischung aus Pilzen, Zwiebeln und Kräutern, die als Füllung oder Geschmacksgrundlage dient."),
        Word(word: "Emulsion", definition: "Eine Mischung aus zwei normalerweise nicht mischbaren Flüssigkeiten, oft Öl und Wasser, stabilisiert durch Emulgatoren."),
        Word(word: "Flambieren", definition: "Eine Technik, bei der Alkohol über ein Gericht gegossen und angezündet wird, um einen besonderen Geschmack zu erzeugen."),
        Word(word: "Ganache", definition: "Eine glatte Mischung aus Schokolade und Sahne, verwendet als Füllung oder Überzug."),
        Word(word: "Harissa", definition: "Eine scharfe nordafrikanische Würzpaste aus Chilis, Knoblauch, Öl und verschiedenen Gewürzen."),
        Word(word: "Infusion", definition: "Das Extrahieren von Aromen aus Zutaten (wie Kräutern oder Tee) durch Einlegen in eine Flüssigkeit, oft Wasser oder Öl."),
        Word(word: "Julienne", definition: "Das Schneiden von Gemüse in dünne, streichholzähnliche Streifen."),
        Word(word: "Mise en place", definition: "Eine französische Phrase, die „alles an seinen Platz“ bedeutet, bezieht sich auf die Vorbereitung und Organisation von Zutaten vor dem Kochen."),
        Word(word: "Nappe", definition: "Ein Begriff, der die Konsistenz einer Flüssigkeit beschreibt, die dick genug ist, um einen Löffel oder ein Lebensmittel leicht zu überziehen."),
        Word(word: "Pochieren", definition: "Das sanfte Garen von Lebensmitteln in einer Flüssigkeit bei relativ niedrigen Temperaturen."),
        Word(word: "Quenelle", definition: "Eine glatte, ovale Form aus weichen Lebensmitteln, oft hergestellt mit zwei Löffeln."),
        Word(word: "Roux", definition: "Eine Mischung aus Fett und Mehl, die als Basis für Saucen verwendet wird."),
        Word(word: "Sashimi", definition: "Ein japanisches Gericht aus sehr dünn geschnittenem, rohem Fisch, oft serviert mit Sojasauce und Wasabi."),
        Word(word: "Tartar", definition: "Ein Gericht, typischerweise aus rohem, fein gehacktem Rindfleisch oder Fisch, oft gewürzt mit Zwiebeln, Kapern und Gewürzen."),
        Word(word: "Umbricelli", definition: "Eine Art dicke, handgemachte italienische Pasta."),
        Word(word: "Xanthan", definition: "Ein Polysaccharid, das als Verdickungsmittel und Stabilisator in vielen Lebensmitteln und kulinarischen Anwendungen verwendet wird."),
        Word(word: "Yuzu", definition: "Eine asiatische Zitrusfrucht, bekannt für ihr unverwechselbares Aroma, das in der japanischen Küche häufig verwendet wird."),
        Word(word: "Zesten", definition: "Das Abreiben der äußeren, farbigen Schale von Zitrusfrüchten, um Aroma zu Speisen und Getränken hinzuzufügen.")
    ]),

    Theme(name: "Geschichte und Geografie", words: [
        Word(word: "Archäologie", definition: "Die Wissenschaft, die sich mit der Erforschung materieller Überreste vergangener menschlicher Lebensweisen befasst."),
        Word(word: "Kartografie", definition: "Die Kunst und Wissenschaft der Landkartenherstellung."),
        Word(word: "Chronologie", definition: "Die Wissenschaft der zeitlichen Einordnung von Ereignissen in der Geschichte."),
        Word(word: "Demografie", definition: "Die statistische Untersuchung von Populationen, insbesondere hinsichtlich Größe, Dichte, Verteilung und Trends."),
        Word(word: "Epoche", definition: "Ein bedeutender Zeitabschnitt in der Geschichte oder im Leben."),
        Word(word: "Feudalismus", definition: "Ein gesellschaftliches System im mittelalterlichen Europa, in dem das Land von Adeligen gehalten wurde, die Vasallen oder Lehnsmänner über ihr Land herrschen ließen."),
        Word(word: "Geopolitik", definition: "Die Untersuchung der Auswirkungen geografischer Faktoren auf die internationale Politik und die Beziehungen zwischen Staaten."),
        Word(word: "Hellenismus", definition: "Die Periode der Verbreitung der griechischen Kultur über den Nahen Osten nach den Eroberungen Alexanders des Großen."),
        Word(word: "Imperialismus", definition: "Die Politik der Ausdehnung der Herrschaft oder des Einflusses eines Staates über andere Staaten oder Gebiete."),
        Word(word: "Jingoismus", definition: "Extremer Patriotismus, insbesondere in der Form aggressiver oder kriegerischer Außenpolitik."),
        Word(word: "Kolonialismus", definition: "Die Praxis der Inbesitznahme und Kontrolle eines Landes durch ein anderes Land."),
        Word(word: "Megalith", definition: "Ein großes vorgeschichtliches Steindenkmal oder -bauwerk."),
        Word(word: "Nationalismus", definition: "Eine politische Ideologie, die die Interessen einer bestimmten Nation als primär ansieht."),
        Word(word: "Orientalismus", definition: "Der Nachahmungs- oder Darstellungsstil des Orients (insbesondere des Nahen Ostens) in der westlichen Welt."),
        Word(word: "Patriarchat", definition: "Ein soziales System, in dem Männer die vorherrschende Autorität in Rollen der politischen Führung, moralischen Autorität, sozialen Privilegien und Kontrolle des Eigentums haben."),
        Word(word: "Quartär", definition: "Die jüngste geologische Periode, die das Pleistozän und Holozän umfasst."),
        Word(word: "Renaissance", definition: "Die Wiedergeburt der Kunst, Kultur und Wissenschaft in Europa zwischen dem 14. und 17. Jahrhundert."),
        Word(word: "Sakralarchitektur", definition: "Der Bau von Gebäuden für religiöse Zwecke oder Rituale."),
        Word(word: "Totalitarismus", definition: "Ein politisches System, in dem der Staat nahezu vollständige Kontrolle über das tägliche Leben der Bürger hat."),
        Word(word: "Utopie", definition: "Ein imaginierter Ort oder Zustand, in dem alles perfekt ist."),
        Word(word: "Völkerwanderung", definition: "Die massiven Wanderungsbewegungen der germanischen Stämme und anderer Volksgruppen in Europa während des 4. bis 6. Jahrhunderts."),
        Word(word: "Weltkrieg", definition: "Ein Krieg, der Nationen aus allen Teilen der Welt betrifft, besonders die beiden Kriege des 20. Jahrhunderts."),
        Word(word: "Xenophobie", definition: "Die Angst oder Abneigung gegenüber Menschen aus anderen Ländern."),
        Word(word: "Yuan-Dynastie", definition: "Eine bedeutende Dynastie in China, die von den Mongolen im 13. und 14. Jahrhundert gegründet wurde."),
        Word(word: "Zivilisation", definition: "Eine komplexe Gesellschaft mit Städten, einer zentralen Regierung, sozialen Klassen und, in der Regel, schriftlichen Kommunikationsformen."),
        Word(word: "Absolutismus", definition: "Ein politisches System, in dem ein Herrscher uneingeschränkte Macht hat."),
        Word(word: "Byzantinisch", definition: "Relativ zum Oströmischen Reich oder seiner Kultur, Kunst oder Geschichte."),
        Word(word: "Dekolonisation", definition: "Der Prozess, durch den Kolonien unabhängig von den kolonisierenden Ländern werden."),
        Word(word: "Enklave", definition: "Ein Gebiet oder eine Gruppe, die vollständig von einem fremden Territorium umgeben ist."),
        Word(word: "Frontier", definition: "Eine Grenze zwischen zwei Ländern oder die äußerste Grenze der besiedelten oder erkundeten Gebiete eines Landes.")
    ])

]
